apiVersion: v1
kind: Pod
metadata:
  labels:
    tier: db
  name: redis
spec:
  schedulerName: my-scheduler
  containers:
  - image: redis:alpine
    name: redis
  dnsPolicy: ClusterFirst
  restartPolicy: Always